# LoadBalancer Test Application
# This creates test pods and services to verify Azure LoadBalancer communication

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb-test-app
  namespace: default
  labels:
    app: lb-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lb-test
  template:
    metadata:
      labels:
        app: lb-test
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: lb-test-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lb-test-html
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>LoadBalancer Test - Pod Info</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 40px; background: #f5f5f5; }
            .container { background: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
            .pod-info { background: #e8f4f8; padding: 15px; border-radius: 5px; margin: 10px 0; }
            .timestamp { color: #666; font-size: 0.9em; }
            .refresh { background: #007cba; color: white; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🚀 LoadBalancer Test Application</h1>
            <div class="pod-info">
                <h3>Pod Information:</h3>
                <p><strong>Pod Name:</strong> <span id="pod-name">Loading...</span></p>
                <p><strong>Pod IP:</strong> <span id="pod-ip">Loading...</span></p>
                <p><strong>Node Name:</strong> <span id="node-name">Loading...</span></p>
                <p><strong>Request Time:</strong> <span id="timestamp">Loading...</span></p>
            </div>
            <button class="refresh" onclick="location.reload()">🔄 Refresh Page</button>
            <p class="timestamp">This page shows which pod is handling your request, proving load balancing is working!</p>
        </div>
        <script>
            document.getElementById('pod-name').textContent = '{{POD_NAME}}';
            document.getElementById('pod-ip').textContent = '{{POD_IP}}';
            document.getElementById('node-name').textContent = '{{NODE_NAME}}';
            document.getElementById('timestamp').textContent = new Date().toLocaleString();
        </script>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: lb-test-service
  namespace: default
  labels:
    app: lb-test
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: lb-test
---
# Alternative ClusterIP service for comparison
apiVersion: v1
kind: Service
metadata:
  name: lb-test-clusterip
  namespace: default
  labels:
    app: lb-test
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: lb-test
---
# NodePort service for additional testing
apiVersion: v1
kind: Service
metadata:
  name: lb-test-nodeport
  namespace: default
  labels:
    app: lb-test
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: lb-test
