# Common Namespaces for Applications
# Following DRY principle - single file for all application namespaces

apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    name: argocd
    app.kubernetes.io/name: argocd
    app.kubernetes.io/part-of: msdp-platform
    app.kubernetes.io/component: gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: backstage
  labels:
    name: backstage
    app.kubernetes.io/name: backstage
    app.kubernetes.io/part-of: msdp-platform
    app.kubernetes.io/component: developer-portal
---
apiVersion: v1
kind: Namespace
metadata:
  name: crossplane-system
  labels:
    name: crossplane-system
    app.kubernetes.io/name: crossplane
    app.kubernetes.io/part-of: msdp-platform
    app.kubernetes.io/component: infrastructure-management
