apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: crossplane-providers
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - aws-provider.yaml
  - azure-provider.yaml

namespace: crossplane-system
