apiVersion: msdp.io/v1alpha1
kind: XBackstageInfrastructure
metadata:
  name: backstage-dev-platform-core-global
  namespace: crossplane-system
  labels:
    environment: dev
    business-unit: platform-core
    country: global
    service: backstage
spec:
  # Environment Configuration
  environment: "dev"
  businessUnit: "platform-core"
  country: "global"

  # Azure Configuration
  location: "UK South"
  resourceGroupName: "msdp-dev-rg"
  tenantId: "${AZURE_TENANT_ID}"

  # PostgreSQL Configuration (Dev - Smaller, cheaper)
  postgresAdminUser: "backstageadmin"
  postgresPasswordSecret: "backstage-postgres-password-dev"
  postgresSku: "B_Standard_B1ms"
  postgresVersion: "13"
  postgresStorageMb: 32768
  postgresBackupRetentionDays: 3
  postgresGeoRedundantBackup: false
  postgresCharset: "UTF8"
  postgresCollation: "en_US.utf8"
  postgresStartIp: "0.0.0.0"
  postgresEndIp: "255.255.255.255"

  # Storage Configuration (Dev - Standard tier)
  storageAccountTier: "Standard"
  storageAccountReplication: "LRS"
  storageAccountKind: "StorageV2"
  storageMinTlsVersion: "TLS1_2"
  storageAllowPublic: false
  storageContainerAccessType: "private"

  # Key Vault Configuration (Dev - Standard features)
  keyVaultSku: "standard"
  keyVaultDiskEncryption: true
  keyVaultTemplateDeployment: true
  keyVaultRbacAuth: true
  keyVaultPurgeProtection: false

  # Application Insights Configuration (Dev - Basic monitoring)
  appInsightsType: "web"
  appInsightsRetentionDays: 30
  appInsightsDailyDataCap: 0.1
  appInsightsDataCapNotificationsDisabled: true
