# Azure Database Claim Example
apiVersion: delivery-platform.io/v1alpha1
kind: Database
metadata:
  name: delivery-platform-azure-db
  namespace: default
spec:
  provider: azure
  environment: dev
  region: "East US"
  azure-resource-group: delivery-platform-rg
  azure-location: "East US"
