#!/bin/bash

# Git Operations Script for MSDP Platform
set -e

echo "=== MSDP Platform Git Operations ==="
echo "Working directory: $(pwd)"
echo "Date: $(date)"
echo ""

# Check if we're in a git repository
if [ ! -d ".git" ]; then
    echo "Initializing git repository..."
    git init
    echo "✅ Git repository initialized"
else
    echo "✅ Git repository already exists"
fi

# Check current status
echo ""
echo "=== Current Git Status ==="
git status --porcelain || echo "No changes to commit"

# Add all files
echo ""
echo "=== Adding Files to Git ==="
git add .
echo "✅ All files added to git"

# Check what's staged
echo ""
echo "=== Staged Files ==="
git diff --cached --name-only | head -20
if [ $(git diff --cached --name-only | wc -l) -gt 20 ]; then
    echo "... and $(($(git diff --cached --name-only | wc -l) - 20)) more files"
fi

# Commit changes
echo ""
echo "=== Committing Changes ==="
git commit -m "Add OIDC validation workflow and terraform-backend action

- Created .github/workflows/oidc-validate.yaml for readiness-only validation
- Created actions/terraform-backend/ composite action
- Workflow validates OIDC auth and backend primitives without running terraform
- Single source of truth: backend-config.json generated by terraform-backend action
- No terraform init/plan/apply operations in validation workflow
- Added guard against terraform execution in validation workflow
- Updated workflow formatting and improved error handling"

echo "✅ Changes committed successfully"

# Check if remote exists
echo ""
echo "=== Checking Remote Configuration ==="
if git remote get-url origin >/dev/null 2>&1; then
    echo "✅ Remote origin found: $(git remote get-url origin)"
    
    # Get current branch
    CURRENT_BRANCH=$(git branch --show-current)
    echo "Current branch: $CURRENT_BRANCH"
    
    # Push to remote
    echo ""
    echo "=== Pushing to Remote ==="
    if git push origin $CURRENT_BRANCH; then
        echo "✅ Successfully pushed to remote!"
    else
        echo "❌ Failed to push to remote. Trying to push to main branch..."
        if git push origin main; then
            echo "✅ Successfully pushed to main branch!"
        else
            echo "❌ Failed to push to main branch. Please check your remote configuration."
        fi
    fi
else
    echo "❌ No remote origin found."
    echo ""
    echo "To add a remote, run:"
    echo "git remote add origin <your-repo-url>"
    echo "Then run: git push -u origin main"
    echo ""
    echo "Current remotes:"
    git remote -v || echo "No remotes configured"
fi

echo ""
echo "=== Git Operations Summary ==="
echo "✅ Repository initialized/updated"
echo "✅ Files added and committed"
if git remote get-url origin >/dev/null 2>&1; then
    echo "✅ Changes pushed to remote"
else
    echo "⚠️  No remote configured - please add remote and push manually"
fi
echo ""
echo "=== Git Operations Completed! ==="
