# MSDP Aurora Serverless Composition
# Provides Aurora PostgreSQL Serverless v2 for MSDP services

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: msdp-aurora-serverless
  labels:
    provider: aws
    service: database
    msdp.platform/composition: aurora-serverless
    msdp.platform/managed-by: terraform
spec:
  compositeTypeRef:
    apiVersion: msdp.platform/v1alpha1
    kind: XAuroraServerless
  
  resources:
  # DB Subnet Group
  - name: db-subnet-group
    base:
      apiVersion: rds.aws.crossplane.io/v1alpha1
      kind: DBSubnetGroup
      spec:
        forProvider:
          region: eu-west-1
          description: "MSDP Aurora Serverless subnet group"
          subnetIds:
            - subnet-0123456789abcdef0  # Replace with actual subnet IDs
            - subnet-0123456789abcdef1
          tags:
            Environment: dev
            Project: msdp
            Component: database
            ManagedBy: crossplane
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.region
      toFieldPath: spec.forProvider.region
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.environment
      toFieldPath: spec.forProvider.tags.Environment
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.dbSubnetGroupName
      transforms:
      - type: string
        string:
          fmt: "msdp-%s-subnet-group"

  # Aurora Cluster
  - name: aurora-cluster
    base:
      apiVersion: rds.aws.crossplane.io/v1alpha1
      kind: Cluster
      spec:
        forProvider:
          region: eu-west-1
          engine: aurora-postgresql
          engineMode: provisioned
          engineVersion: "15.4"
          serverlessV2ScalingConfiguration:
            maxCapacity: 16
            minCapacity: 0.5
          databaseName: msdp
          masterUsername: msdp_admin
          storageEncrypted: true
          backupRetentionPeriod: 7
          preferredBackupWindow: "03:00-04:00"
          preferredMaintenanceWindow: "sun:04:00-sun:05:00"
          skipFinalSnapshot: true  # For dev environment
          
          # Security
          vpcSecurityGroupIds:
            - sg-0123456789abcdef0  # Replace with actual security group ID
          
          tags:
            Environment: dev
            Project: msdp
            Component: database
            ManagedBy: crossplane
            Service: aurora-serverless
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.clusterIdentifier
      toFieldPath: spec.forProvider.clusterIdentifier
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.region
      toFieldPath: spec.forProvider.region
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.environment
      toFieldPath: spec.forProvider.tags.Environment
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.serviceName
      toFieldPath: spec.forProvider.tags.Service
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.minCapacity
      toFieldPath: spec.forProvider.serverlessV2ScalingConfiguration.minCapacity
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.maxCapacity
      toFieldPath: spec.forProvider.serverlessV2ScalingConfiguration.maxCapacity
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.skipFinalSnapshot
      toFieldPath: spec.forProvider.skipFinalSnapshot
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.backupRetentionPeriod
      toFieldPath: spec.forProvider.backupRetentionPeriod
    - type: PatchSet
      patchSetName: db-subnet-group-ref
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.endpoint
      toFieldPath: status.endpoint
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.readerEndpoint
      toFieldPath: status.readerEndpoint
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.port
      toFieldPath: status.port

  # Connection Secret
  - name: aurora-connection-secret
    base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: v1
            kind: Secret
            metadata:
              namespace: default  # Will be patched
            type: Opaque
            data:
              endpoint: ""  # Will be patched
              port: "5432"
              database: "msdp"
              username: "msdp_admin"
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.namespace
      toFieldPath: spec.forProvider.manifest.metadata.namespace
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.manifest.metadata.name
      transforms:
      - type: string
        string:
          fmt: "%s-aurora-connection"
    - type: FromCompositeFieldPath
      fromFieldPath: status.endpoint
      toFieldPath: spec.forProvider.manifest.data.endpoint
      transforms:
      - type: string
        string:
          type: Convert
          convert: "base64"
    - type: FromCompositeFieldPath
      fromFieldPath: status.port
      toFieldPath: spec.forProvider.manifest.data.port
      transforms:
      - type: string
        string:
          type: Convert
          convert: "base64"

  patchSets:
  - name: db-subnet-group-ref
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.dbSubnetGroupName
      transforms:
      - type: string
        string:
          fmt: "msdp-%s-subnet-group"
