# Cert-Manager Configuration
cert_manager:
  # Global configuration
  global:
    leaderElection:
      namespace: cert-manager
  
  # Install CRDs
  installCRDs: true
  
  # Image configuration
  image:
    registry: quay.io
    repository: jetstack/cert-manager-controller
    pullPolicy: IfNotPresent
  
  # Webhook configuration
  webhook:
    image:
      registry: quay.io
      repository: jetstack/cert-manager-webhook
      pullPolicy: IfNotPresent
  
  # CA Injector configuration
  cainjector:
    image:
      registry: quay.io
      repository: jetstack/cert-manager-cainjector
      pullPolicy: IfNotPresent
  
  # Resource configuration
  resources:
    requests:
      cpu: "10m"
      memory: "32Mi"
    limits:
      cpu: "100m"
      memory: "128Mi"
  
  # Webhook resources
  webhook:
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
  
  # CA Injector resources
  cainjector:
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
  
  # Security context
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 1000
  
  # Node selector
  nodeSelector:
    kubernetes.io/os: linux
  
  # Tolerations
  tolerations: []
  
  # Affinity
  affinity: {}
  
  # Pod annotations
  podAnnotations: {}
  
  # Service account
  serviceAccount:
    create: true
    annotations: {}
  
  # RBAC
  rbac:
    create: true
  
  # Prometheus monitoring
  prometheus:
    enabled: true
    servicemonitor:
      enabled: true
      namespace: "monitoring"
