# Prometheus Configuration
prometheus:
  # Global configuration
  global:
    scrape_interval: 15s
    evaluation_interval: 15s

  # Server configuration
  server:
    replica_count: 1

    # Image configuration
    image:
      repository: quay.io/prometheus/prometheus
      pullPolicy: IfNotPresent

    # Resource configuration
    resources:
      requests:
        cpu: "200m"
        memory: "512Mi"
      limits:
        cpu: "1000m"
        memory: "2Gi"

    # Persistence configuration
    persistentVolume:
      enabled: true
      size: "50Gi"
      storage_class: ""

    # Retention configuration
    retention: "15d"

    # Service configuration
    service:
      type: ClusterIP
      port: 80
      target_port: 9090

    # Ingress configuration
    ingress:
      enabled: false # Usually accessed via Grafana

    # Node selector
    nodeSelector:
      kubernetes.io/os: linux

    # Tolerations
    tolerations: []

    # Affinity
    affinity: {}

  # Alertmanager configuration
  alertmanager:
    enabled: true
    replica_count: 1

    # Image configuration
    image:
      repository: quay.io/prometheus/alertmanager
      pullPolicy: IfNotPresent

    # Resource configuration
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "512Mi"

    # Persistence configuration
    persistentVolume:
      enabled: true
      size: "10Gi"
      storage_class: ""

    # Service configuration
    service:
      type: ClusterIP
      port: 80
      target_port: 9093

  # Pushgateway configuration
  pushgateway:
    enabled: true

    # Image configuration
    image:
      repository: quay.io/prometheus/pushgateway
      pullPolicy: IfNotPresent

    # Resource configuration
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "512Mi"

    # Service configuration
    service:
      type: ClusterIP
      port: 80
      target_port: 9091

  # Node exporter configuration
  nodeExporter:
    enabled: true

    # Image configuration
    image:
      repository: quay.io/prometheus/node-exporter
      pullPolicy: IfNotPresent

    # Resource configuration
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"

  # Kube state metrics configuration
  kubeStateMetrics:
    enabled: true

    # Image configuration
    image:
      repository: registry.k8s.io/kube-state-metrics/kube-state-metrics
      pullPolicy: IfNotPresent

    # Resource configuration
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "512Mi"

  # Service monitors
  serviceMonitors:
    enabled: true
    namespace: "monitoring"
