# Shared Configuration for GitHub Actions Workflows
# This file centralizes version management and common configuration

# Tool Versions
terraform_version: "1.9.5"
python_version: "3.11"
node_version: "18"
kubectl_version: "1.28.0"
helm_version: "3.12.0"

# GitHub Action Versions
actions:
  checkout: "v4"
  setup_terraform: "v3"
  setup_python: "v4"
  setup_node: "v4"
  upload_artifact: "v4"
  download_artifact: "v4"
  cache: "v3"

# Cloud Configuration
aws:
  default_region: "eu-west-1"
  account_id: "319422413814"

azure:
  default_location: "uksouth"

# Common Environment Variables
common_env:
  TF_INPUT: "false"
  ARM_USE_OIDC: "true"
  PYTHONUNBUFFERED: "1"

# Timeout Configuration (in minutes)
timeouts:
  terraform_init: 10
  terraform_plan: 20
  terraform_apply: 60
  terraform_destroy: 30
  kubernetes_validation: 15
  helm_install: 20

# Cache Configuration
cache:
  terraform_providers: "~/.terraform.d/plugin-cache"
  python_packages: "~/.cache/pip"
  node_modules: "~/.npm"

# Retry Configuration
retry:
  max_attempts: 3
  delay_seconds: 30
