---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterissuers.cert-manager.io
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/version: "v1.13.2"
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: cert-manager
    app.kubernetes.io/managed-by: kustomize
spec:
  group: cert-manager.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                acme:
                  type: object
                  properties:
                    server:
                      type: string
                    email:
                      type: string
                    privateKeySecretRef:
                      type: object
                      properties:
                        name:
                          type: string
                    solvers:
                      type: array
                      items:
                        type: object
                        properties:
                          http01:
                            type: object
                            properties:
                              ingress:
                                type: object
                                properties:
                                  class:
                                    type: string
  scope: Cluster
  names:
    plural: clusterissuers
    singular: clusterissuer
    kind: ClusterIssuer
    shortNames:
      - ci
