# Cert-Manager Helm Values
# This file contains the configuration for Cert-Manager v1.18.0

# Install CRDs
installCRDs: true

# Global configuration
global:
  leaderElection:
    namespace: cert-manager

# Image configuration
image:
  registry: quay.io
  repository: jetstack/cert-manager-controller
  tag: "v1.18.0"
  pullPolicy: IfNotPresent

# Webhook configuration
webhook:
  image:
    registry: quay.io
    repository: jetstack/cert-manager-webhook
    tag: "v1.18.0"
    pullPolicy: IfNotPresent

# CA Injector configuration
cainjector:
  image:
    registry: quay.io
    repository: jetstack/cert-manager-cainjector
    tag: "v1.18.0"
    pullPolicy: IfNotPresent

# Service account configuration
serviceAccount:
  create: true
  name: ""

# Prometheus monitoring
prometheus:
  enabled: true
  servicemonitor:
    enabled: false # Disabled to avoid dependency on Prometheus Operator CRDs
