apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cert_manager
  annotations:
    config.kubernetes.io/local-config: "true"
resources:
  - namespace.yaml
# Helm chart configuration
helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.18.0
    releaseName: cert-manager
    namespace: cert-manager
    valuesFile: helm-values.yaml
namespace: cert-manager
