apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cert-manager
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - namespace.yaml
  - crds.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - letsencrypt-issuer.yaml

commonLabels:
  app.kubernetes.io/part-of: msdp-platform
  app.kubernetes.io/managed-by: kustomize

namespace: cert-manager
