---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/version: "v1.13.2"
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: cert-manager
    app.kubernetes.io/managed-by: kustomize
