# Test User Workload - Should be scheduled on user nodes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-user-workload
  namespace: default
  labels:
    app: test-user-workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-user-workload
  template:
    metadata:
      labels:
        app: test-user-workload
    spec:
      containers:
        - name: nginx
          image: nginx:1.21
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "200m"
      # No node affinity - should be scheduled on user nodes
---
# Test System Workload - Should be scheduled on system nodes only
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-system-workload
  namespace: default
  labels:
    app: test-system-workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-system-workload
  template:
    metadata:
      labels:
        app: test-system-workload
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.azure.com/mode
                    operator: In
                    values: ["system"]
      containers:
        - name: nginx
          image: nginx:1.21
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "200m"
