apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: external-dns
  namespace: external-dns
  labels:
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/component: dns-controller
    monitoring: enabled
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: external-dns
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
