apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: crossplane
  annotations:
    config.kubernetes.io/local-config: "true"

resources: []

# Helm chart configuration
helmCharts:
  - name: crossplane
    repo: https://charts.crossplane.io/stable
    version: 2.0.2
    releaseName: crossplane
    namespace: crossplane-system
    valuesFile: helm-values.yaml

namespace: crossplane-system
