apiVersion: v1
kind: Namespace
metadata:
  name: crossplane-system
  labels:
    app.kubernetes.io/name: crossplane
    app.kubernetes.io/part-of: msdp-platform
    app.kubernetes.io/managed-by: kustomize
