# Azure Key Vault ClusterSecretStore for External Secrets Operator
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault-store
  namespace: external-secrets
spec:
  provider:
    azurekv:
      vaultUrl: "https://msdp-certificates-kv.vault.azure.net/"
      tenantId: "a4474822-c84f-4bd1-bc35-baed17234c9f"
      authType: "WorkloadIdentity"
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets
