# Argo CD custom values rendered by Terraform

server:
  ingress:
    enabled: true
    ingressClassName: ${ingress_class_name}
    hosts:
      - ${hostname}
    annotations:
${ingress_annotations}
    paths:
      - /
    pathType: Prefix
    tls:
      - secretName: ${tls_secret_name}
        hosts:
          - ${hostname}
  extraArgs:
%{ for arg in server_extra_args ~}
    - ${arg}
%{ endfor }

configs:
  cm:
    url: https://${hostname}

applicationSet:
  enabled: false

notifications:
  enabled: false
