# Development Environment Configuration
# Clean, simple configuration for multi-cloud infrastructure

environment: dev

# AWS Configuration
aws:
  # Region
  region: eu-west-1
  
  # Network Configuration
  network:
    vpc_name: vpc-msdp-dev
    vpc_cidr: 10.50.0.0/16
    availability_zones: ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
    
    public_subnets:
      - name: subnet-public-dev-1a
        cidr: 10.50.1.0/24
        availability_zone: eu-west-1a
      - name: subnet-public-dev-1b
        cidr: 10.50.2.0/24
        availability_zone: eu-west-1b
      - name: subnet-public-dev-1c
        cidr: 10.50.3.0/24
        availability_zone: eu-west-1c
    
    private_subnets:
      - name: subnet-private-dev-1a
        cidr: 10.50.11.0/24
        availability_zone: eu-west-1a
      - name: subnet-private-dev-1b
        cidr: 10.50.12.0/24
        availability_zone: eu-west-1b
      - name: subnet-private-dev-1c
        cidr: 10.50.13.0/24
        availability_zone: eu-west-1c
  
  # EKS Configuration
  eks:
    clusters:
      - name: eks-msdp-dev-01
        kubernetes_version: "1.31"
        endpoint_private_access: true
        endpoint_public_access: true
        public_access_cidrs: ["0.0.0.0/0"]
        
        node_groups:
          - name: system-nodes
            instance_types: ["t3.medium"]
            capacity_type: ON_DEMAND
            min_size: 2
            max_size: 4
            desired_size: 2
            disk_size: 20
            ami_type: AL2_x86_64
            
          - name: user-nodes
            instance_types: ["t3.large"]
            capacity_type: SPOT
            min_size: 1
            max_size: 10
            desired_size: 2
            disk_size: 50
            ami_type: AL2_x86_64
      
      - name: eks-msdp-dev-02
        kubernetes_version: "1.31"
        endpoint_private_access: true
        endpoint_public_access: true
        public_access_cidrs: ["0.0.0.0/0"]
        
        node_groups:
          - name: system-nodes
            instance_types: ["t3.small"]
            capacity_type: ON_DEMAND
            min_size: 1
            max_size: 2
            desired_size: 1
            disk_size: 20
            ami_type: AL2_x86_64

# Azure Configuration
azure:
  # Location
  location: uksouth
  
  # Network Configuration
  network:
    resource_group_name: rg-msdp-network-dev
    vnet_name: vnet-msdp-dev
    vnet_cidr: 10.60.0.0/16
    
    subnets:
      - name: snet-aks-system-dev
        cidr: 10.60.1.0/24
        create_nsg: true
      - name: snet-aks-user-dev
        cidr: 10.60.2.0/24
        create_nsg: true
  
  # AKS Configuration
  aks:
    clusters:
      - name: aks-msdp-dev-01
        kubernetes_version: "1.31.2"
        system_node_count: 2
        system_vm_size: Standard_D2s_v3
        user_vm_size: Standard_D4s_v3
        user_min_count: 1
        user_max_count: 5
        user_spot_enabled: false
      
      - name: aks-msdp-dev-02
        kubernetes_version: "1.31.2"
        system_node_count: 1
        system_vm_size: Standard_D2s_v3
        user_vm_size: Standard_D2s_v3
        user_min_count: 0
        user_max_count: 3
        user_spot_enabled: true

# Global Tags
tags:
  Environment: dev
  Project: msdp
  ManagedBy: terraform
  Owner: platform-team
  CostCenter: engineering
