apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xaksclusters.msdp.io
spec:
  group: msdp.io
  names:
    kind: XAKSCluster
    plural: xaksclusters
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                # Environment Configuration
                environment:
                  type: string
                  description: "Environment (dev, staging, prod)"
                  enum: ["dev", "staging", "prod"]
                  default: "dev"
                businessUnit:
                  type: string
                  description: "Business Unit (food-delivery, grocery-delivery, cleaning-services, repair-services)"
                  enum:
                    [
                      "food-delivery",
                      "grocery-delivery",
                      "cleaning-services",
                      "repair-services",
                      "platform-core",
                    ]
                  default: "platform-core"
                country:
                  type: string
                  description: "Country code (uk, india)"
                  enum: ["uk", "india", "global"]
                  default: "global"
                # Azure Configuration
                location:
                  type: string
                  description: "Azure region"
                  default: "eastus"
                resourceGroupName:
                  type: string
                  description: "Azure Resource Group name"
                subscriptionId:
                  type: string
                  description: "Azure Subscription ID"
                # AKS Cluster Configuration
                clusterName:
                  type: string
                  description: "AKS cluster name"
                kubernetesVersion:
                  type: string
                  description: "Kubernetes version"
                  default: "1.32.6"
                dnsPrefix:
                  type: string
                  description: "DNS prefix for the cluster"
                # System Node Pool Configuration
                systemNodePool:
                  type: object
                  properties:
                    name:
                      type: string
                      default: "system"
                    vmSize:
                      type: string
                      default: "Standard_B2s"
                    nodeCount:
                      type: integer
                      default: 1
                    minCount:
                      type: integer
                      default: 1
                    maxCount:
                      type: integer
                      default: 2
                    enableAutoScaling:
                      type: boolean
                      default: true
                    mode:
                      type: string
                      enum: ["System", "User"]
                      default: "System"
                    osType:
                      type: string
                      enum: ["Linux", "Windows"]
                      default: "Linux"
                    osSku:
                      type: string
                      enum:
                        ["Ubuntu", "AzureLinux", "Windows2019", "Windows2022"]
                      default: "Ubuntu"
                # User Node Pool Configuration
                userNodePool:
                  type: object
                  properties:
                    name:
                      type: string
                      default: "user"
                    vmSize:
                      type: string
                      default: "Standard_B2s"
                    nodeCount:
                      type: integer
                      default: 0
                    minCount:
                      type: integer
                      default: 0
                    maxCount:
                      type: integer
                      default: 3
                    enableAutoScaling:
                      type: boolean
                      default: true
                    mode:
                      type: string
                      enum: ["System", "User"]
                      default: "User"
                    osType:
                      type: string
                      enum: ["Linux", "Windows"]
                      default: "Linux"
                    osSku:
                      type: string
                      enum:
                        ["Ubuntu", "AzureLinux", "Windows2019", "Windows2022"]
                      default: "Ubuntu"
                    priority:
                      type: string
                      enum: ["Regular", "Spot"]
                      default: "Spot"
                    evictionPolicy:
                      type: string
                      enum: ["Delete", "Deallocate"]
                      default: "Delete"
                    spotMaxPrice:
                      type: number
                      default: -1
                # Network Configuration
                networkPlugin:
                  type: string
                  enum: ["azure", "kubenet"]
                  default: "azure"
                networkPolicy:
                  type: string
                  enum: ["azure", "calico"]
                  default: "azure"
                serviceCidr:
                  type: string
                  default: "10.0.0.0/16"
                dnsServiceIp:
                  type: string
                  default: "10.0.0.10"
                # Security Configuration
                enableRbac:
                  type: boolean
                  default: true
                enableManagedIdentity:
                  type: boolean
                  default: true
                enableAadIntegration:
                  type: boolean
                  default: false
                # Monitoring Configuration
                enableMonitoring:
                  type: boolean
                  default: true
                enableLogAnalytics:
                  type: boolean
                  default: true
                # Cost Optimization
                enableCostOptimization:
                  type: boolean
                  default: true
                enableSpotInstances:
                  type: boolean
                  default: true
                # Tags
                tags:
                  type: object
                  additionalProperties:
                    type: string
                  default:
                    Environment: "dev"
                    Project: "MSDP"
                    CostOptimized: "true"
              required:
                - environment
                - businessUnit
                - country
                - location
                - resourceGroupName
                - subscriptionId
                - clusterName
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
                connectionDetails:
                  type: object
                  properties:
                    clusterName:
                      type: string
                    resourceGroupName:
                      type: string
                    location:
                      type: string
                    kubernetesVersion:
                      type: string
                    fqdn:
                      type: string
                    privateFqdn:
                      type: string
                    nodeResourceGroup:
                      type: string
                    kubeConfig:
                      type: string
