# Development Environment Configuration
# This file consolidates configuration from config/envs/dev.yaml and infrastructure/config/globals.yaml

environment:
  name: dev
  full_name: "Development"
  account_type: dev

# Backend configuration
backend:
  aws:
    account_id: "319422413814"
    region: "eu-west-1"

# Azure configuration
azure:
  subscription_id: "ecd977ed-b8df-4eb6-9cba-98397e1b2491"
  tenant_id: "{{ AZURE_TENANT_ID }}"  # Will be replaced by secrets in workflows
  location: "uksouth"
  
  # Resource naming
  resource_group: "dev-ops"
  vnet_name: "dev-ops"
  vnet_cidr: "10.60.0.0/16"
  
  # Legacy single subnet config (for backward compatibility)
  subnet_name: "snet-aks-dev"
  subnet_cidr: "10.60.1.0/24"
  aks_name: "aks-dev-01"
  
  # Modern multi-cluster configuration
  aks_clusters:
    - name: "dev-ops-01"
      size: "large"
      subnet_name: "snet-dev-ops-01"
    - name: "dev-ops-02"
      size: "large"
      subnet_name: "snet-dev-ops-02"
  
  # Kubernetes configuration
  kubernetes_version: "1.29.7"
  network_profile:
    plugin: "azure"
    policy: "azure"
    lb_sku: "standard"
    outbound_type: "loadBalancer"

# AWS configuration (for future use)
aws:
  account_id: "319422413814"
  region: "eu-west-1"

# Global settings
global:
  org: "msdp"
  base_domain: "aztech-msdp.com"
  git_org: "msdp-platform"
  
  # Default registry
  default_registry: "ghcr"
  registries:
    ghcr: "ghcr.io/msdp-platform"
    aws_ecr: "public.ecr.aws/msdp"
    azure_acr: "msdp.azurecr.io"
  
  # Kubernetes defaults
  k8s_defaults:
    version: "1.29"
    ingress_class: "nginx"
    cert_issuer: "letsencrypt-prod"
  
  # Security baseline
  security_baseline:
    sign_images: false
    image_scan: true
    branch_protection: true

# Tags applied to all resources
tags:
  Environment: "dev"
  Project: "msdp"
  ManagedBy: "terraform"
  Owner: "platform-team"