# Production Environment Configuration
environment: prod
cluster:
  name: msdp-infra-aks-prod
  resourceGroup: delivery-platform-aks-rg-prod
  location: eastus
  kubernetesVersion: "1.32.6"
  nodeCount: 3
  nodeVmSize: "Standard_D4s_v3"
  minCount: 3
  maxCount: 10

# Crossplane Configuration
crossplane:
  namespace: crossplane-system
  version: "2.0.2"
  providers:
    azure:
      version: "v2.0.1"
    aws:
      version: "v0.44.0"
    gcp:
      version: "v2.0.1"

# ArgoCD Configuration
argocd:
  namespace: argocd
  version: "stable"
  server:
    serviceType: LoadBalancer
    replicas: 3
  controller:
    replicas: 3
  repoServer:
    replicas: 3
  applicationSet:
    replicas: 2
  notifications:
    replicas: 2
  dex:
    replicas: 2
  redis:
    replicas: 2

# Backstage Configuration
backstage:
  namespace: backstage
  version: "0.1.0"
  replicas: 3
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "2000m"
      memory: "2Gi"
  postgres:
    enabled: true
    host: "backstage-postgres-prod"
    port: 5432
    database: "backstage"
    user: "backstage"
  app:
    title: "MSDP Developer Portal - Production"
    baseUrl: "https://backstage.aztech-msdp.com"

# Networking Configuration
networking:
  ingress:
    className: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
  domains:
    argocd: "argocd.aztech-msdp.com"
    backstage: "backstage.aztech-msdp.com"
    app: "app.aztech-msdp.com"

# Security Configuration
security:
  certManager:
    enabled: true
    clusterIssuer: "letsencrypt-prod"
  rbac:
    enabled: true
  networkPolicies:
    enabled: true

# Monitoring Configuration
monitoring:
  enabled: true
  prometheus:
    enabled: true
  grafana:
    enabled: true
  alertManager:
    enabled: true

# Cost Optimization
costOptimization:
  enabled: true
  spotInstances:
    enabled: false # Production uses regular instances for stability
  autoScaling:
    enabled: true
  scaleToZero:
    enabled: false

# Tags
tags:
  Environment: "prod"
  Project: "MSDP"
  CostOptimized: "false"
  ManagedBy: "GitOps"
