apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: grafana
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - namespace.yaml

# Helm chart configuration
helmCharts:
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    version: 6.61.0
    releaseName: grafana
    namespace: grafana
    valuesFile: helm-values.yaml

commonLabels:
  app.kubernetes.io/part-of: msdp-platform
  app.kubernetes.io/managed-by: kustomize

namespace: grafana
