name: "Terraform Checks"
description: "Composite action to run Terraform formatting and validation checks using Python."

inputs:
  working-directory:
    description: "Directory containing Terraform configuration."
    required: true

runs:
  using: "composite"
  steps:
    - name: Run Terraform Format Check (Python)
      shell: python
      run: |
        import subprocess, sys, os
        wd = os.environ.get('INPUT_WORKING_DIRECTORY', '.')
        os.chdir(wd)
        result = subprocess.run(['terraform', 'fmt', '-check', '-recursive'], capture_output=True)
        if result.returncode != 0:
            print("❌ Terraform files are not properly formatted")
            print(result.stdout.decode())
            print(result.stderr.decode())
            sys.exit(1)
        print("✅ Terraform formatting check passed")
    - name: Run Terraform Validate (Python)
      shell: python
      run: |
        import subprocess, sys, os
        wd = os.environ.get('INPUT_WORKING_DIRECTORY', '.')
        os.chdir(wd)
        result = subprocess.run(['terraform', 'validate'], capture_output=True)
        if result.returncode != 0:
            print("❌ Terraform validation failed")
            print(result.stdout.decode())
            print(result.stderr.decode())
            sys.exit(1)
        print("✅ Terraform validation passed")
