inputs:
  size:
    description: Optional subnet size override (large|medium|small)
    required: false
    default: ""
name: "Generate Network tfvars"
description: "Generates network.auto.tfvars.json from config files for Azure network stack."
runs:
  using: "composite"
  steps:
    - name: Install Python dependencies
      shell: bash
      run: pip install pyyaml
    - name: Generate network.auto.tfvars.json
      shell: bash
      env:
        INPUT_SIZE: ${{ inputs.size || '' }}
      run: python .github/scripts/generate_network_tfvars.py
