apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: prometheus
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - namespace.yaml

# Helm chart configuration
helmCharts:
  - name: prometheus
    repo: https://prometheus-community.github.io/helm-charts
    version: 25.8.2
    releaseName: prometheus
    namespace: monitoring
    valuesFile: helm-values.yaml

commonLabels:
  app.kubernetes.io/part-of: msdp-platform
  app.kubernetes.io/managed-by: kustomize

namespace: monitoring
