# Test Environment Configuration
environment: "test"

# Cluster Configuration
cluster:
  name: "msdp-infra-aks-test"
  resource_group: "delivery-platform-aks-rg-test"
  location: "East US"

# Environment-specific overrides
overrides:
  # Test-specific resource limits (balanced for testing)
  resources:
    grafana:
      requests:
        cpu: "150m"
        memory: "384Mi"
      limits:
        cpu: "750m"
        memory: "1.5Gi"
    
    prometheus:
      requests:
        cpu: "250m"
        memory: "768Mi"
      limits:
        cpu: "1250m"
        memory: "2.5Gi"
    
    argocd:
      requests:
        cpu: "150m"
        memory: "384Mi"
      limits:
        cpu: "750m"
        memory: "1.5Gi"

  # Test-specific timeouts
  timeouts:
    deployment: 450
    verification: 750
    pod_ready: 450

  # Test-specific configurations
  grafana:
    persistence:
      enabled: true
      size: "5Gi"
    admin_password: "test123"  # Test password
  
  prometheus:
    retention: "15d"  # Medium retention for testing
    storage_size: "20Gi"
