# Production Environment Overrides
global:
  environment: "prod"
  namespace: "backstage-prod"

backstage:
  app:
    title: "MSDP Developer Portal - Production"
    baseUrl: "https://backstage.aztech-msdp.com"

deployment:
  replicas: 3
  image:
    tag: "latest"
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

ingress:
  hosts:
    - host: "backstage.aztech-msdp.com"
      paths:
        - path: "/"
          pathType: "Prefix"
  tls:
    - secretName: "backstage-prod-tls"
      hosts:
        - "backstage.aztech-msdp.com"

monitoring:
  serviceMonitor:
    interval: "15s"

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 70

podDisruptionBudget:
  enabled: true
  minAvailable: 2
