# kube-prometheus-stack custom values rendered by Terraform

prometheusOperator:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

prometheus:
  ingress:
    enabled: true
    ingressClassName: ${ingress_class_name}
    hosts:
      - ${prometheus_hostname}
    annotations:
%{ if length(prometheus_annotations) == 0 }
      {}
%{ else }
%{ for k, v in prometheus_annotations }
      ${k}: ${v}
%{ endfor }
%{ endif }
    tls:
      - secretName: ${prometheus_tls_secret}
        hosts:
          - ${prometheus_hostname}
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

alertmanager:
  ingress:
    enabled: false

grafana:
  ingress:
    enabled: true
    ingressClassName: ${ingress_class_name}
    hosts:
      - ${grafana_hostname}
    annotations:
%{ if length(grafana_annotations) == 0 }
      {}
%{ else }
%{ for k, v in grafana_annotations }
      ${k}: ${v}
%{ endfor }
%{ endif }
    tls:
      - secretName: ${grafana_tls_secret}
        hosts:
          - ${grafana_hostname}
  grafana.ini:
    server:
      root_url: https://${grafana_hostname}
      serve_from_sub_path: false
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
