# Backstage Helm Values
# This file contains the configuration for Backstage
# Following DRY principles and modular configuration

# Global configuration
global:
  imageRegistry: ""

# Backstage configuration - updated for chart v2.6.1 schema
backstage:
  # Image configuration - using latest stable tag
  image:
    repository: ghcr.io/backstage/backstage
    tag: "1.33.5"
    pullPolicy: IfNotPresent

  # Resource limits - increased for stability
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi

# Replica count (moved to root level)
replicaCount: 1

# Service configuration (moved to root level)
service:
  type: ClusterIP
  port: 80
  targetPort: 7007

# Security context (moved to root level)
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

# Environment variables (moved to root level)
env:
  - name: NODE_ENV
    value: "production"
  - name: LOG_LEVEL
    value: "info"
  - name: APP_CONFIG_app_baseUrl
    value: "https://backstage.dev.aztech-msdp.com"
  - name: APP_CONFIG_app_title
    value: "MSDP Developer Portal"
  - name: APP_CONFIG_backend_baseUrl
    value: "https://backstage.dev.aztech-msdp.com"
  - name: APP_CONFIG_backend_cors_origin
    value: "https://backstage.dev.aztech-msdp.com"

# Configuration (moved to root level)
config:
  app:
    title: "MSDP Developer Portal"
    baseUrl: "https://backstage.dev.aztech-msdp.com"
  backend:
    baseUrl: "https://backstage.dev.aztech-msdp.com"
    cors:
      origin: "https://backstage.dev.aztech-msdp.com"
  integrations:
    github:
      - host: github.com
        # Token will be injected via secret
  catalog:
    locations:
      - type: url
        target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all.yaml

# Service monitors configuration
serviceMonitor:
  enabled: true
  labels:
    app.kubernetes.io/part-of: msdp-platform

# RBAC configuration
rbac:
  create: true

# Service account configuration
serviceAccount:
  create: true
  name: ""

# Pod security policy
podSecurityPolicy:
  enabled: false

# Network policy
networkPolicy:
  enabled: false
