apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: backstage
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

namespace: backstage
