# Simple Multi-Cloud Database Composition
# Basic composition for Crossplane v2.0.2 compatibility

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: simple-multi-cloud-database
  labels:
    provider: multi-cloud
    service: database
spec:
  compositeTypeRef:
    apiVersion: delivery-platform.io/v1alpha1
    kind: Database
  resources:
    # AWS RDS PostgreSQL (simplified)
    - name: aws-postgresql
      base:
        apiVersion: rds.aws.crossplane.io/v1alpha1
        kind: DBInstance
        spec:
          forProvider:
            dbInstanceClass: db.t3.micro
            engine: postgres
            engineVersion: "15.4"
            allocatedStorage: 20
            storageType: gp2
            backupRetentionPeriod: 1
            skipFinalSnapshot: true
            deletionProtection: false
            masterUsername: postgres
            masterPasswordSecretRef:
              name: postgresql-admin-password
              key: password
          writeConnectionSecretsToRef:
            name: aws-postgresql-connection-secret
            namespace: default
            keys:
              - username
              - password
              - endpoint
              - port
              - database

    # GCP Cloud SQL PostgreSQL (simplified)
    - name: gcp-postgresql
      base:
        apiVersion: sql.gcp.crossplane.io/v1beta1
        kind: DatabaseInstance
        spec:
          forProvider:
            databaseVersion: POSTGRES_15
            region: us-central1
            settings:
              - tier: db-f1-micro
                diskSize: 10
                diskType: PD_STANDARD
                backupConfiguration:
                  - enabled: false
                ipConfiguration:
                  - ipv4Enabled: true
                    authorizedNetworks:
                      - value: "0.0.0.0/0"
          writeConnectionSecretsToRef:
            name: gcp-postgresql-connection-secret
            namespace: default
            keys:
              - username
              - password
              - endpoint
              - port
              - database

    # Azure Database for PostgreSQL (simplified)
    - name: azure-postgresql
      base:
        apiVersion: dbforpostgresql.azure.crossplane.io/v1beta1
        kind: FlexibleServer
        spec:
          forProvider:
            location: "East US"
            resourceGroupName: "delivery-platform-rg"
            administratorLogin: postgres
            administratorPasswordSecretRef:
              name: postgresql-admin-password
              key: password
            version: "15"
            skuName: Basic_B1ms
            storageMb: 32768
            backupRetentionDays: 1
            geoRedundantBackup: false
            highAvailability:
              mode: Disabled
            network:
              publicNetworkAccess: Enabled
          writeConnectionSecretsToRef:
            name: azure-postgresql-connection-secret
            namespace: default
            keys:
              - username
              - password
              - endpoint
              - port
              - database

---
# Simple Composite Resource Definition
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: simple-databases.delivery-platform.io
spec:
  group: delivery-platform.io
  names:
    kind: SimpleDatabase
    plural: simpledatabases
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                provider:
                  type: string
                  enum: ["aws", "gcp", "azure"]
                environment:
                  type: string
                  enum: ["dev", "staging", "prod"]
              required:
                - provider
                - environment
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
