apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: argocd
  annotations:
    config.kubernetes.io/local-config: "true"
resources:
  - namespace.yaml
# Helm chart configuration
helmCharts:
  - name: argo-cd
    repo: null
    version: 5.53.0
    releaseName: argocd
    namespace: argocd
    valuesFile: helm-values.yaml
namespace: argocd
