apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: spot-nodepool
  annotations:
    kubernetes.io/description: "Cost-optimized NodePool using Spot instances for up to 90% savings"
spec:
  # Template for nodes created by this NodePool
  template:
    metadata:
      labels:
        cost-optimization: "true"
        instance-type: "spot"
    spec:
      # Node requirements
      requirements:
        # Use Spot instances for cost savings
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        # Use Linux nodes
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        # Use AMD64 architecture
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        # Use B-series VMs for cost efficiency (more likely to have Spot availability)
        - key: karpenter.azure.com/sku-family
          operator: In
          values: ["B"]
      # Node class reference (uses default AKS node class)
      nodeClassRef:
        group: karpenter.azure.com
        kind: AKSNodeClass
        name: default
      # Taints to prevent system pods from scheduling on Spot nodes
      taints:
        - key: karpenter.sh/capacity-type
          value: spot
          effect: NoSchedule
      # Node expiration (never expire for stability)
      expireAfter: Never
  # Disruption settings for cost optimization
  disruption:
    # Consolidate nodes when they're empty or underutilized
    consolidationPolicy: WhenEmptyOrUnderutilized
    # Consolidate immediately when possible
    consolidateAfter: 0s
    # Allow up to 30% of nodes to be disrupted at once
    budgets:
      - nodes: 30%
