apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: spot-nodepool
  annotations:
    kubernetes.io/description: "Cost-optimized NodePool using broad SKU selection for maximum Spot availability and cost savings"
spec:
  template:
    metadata:
      labels:
        cost-optimization: "true"
        instance-type: "spot"
        karpenter-strategy: "broad-sku-selection"
    spec:
      requirements:
        # Use Spot instances for maximum cost savings
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        # Use Linux nodes
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        # Use AMD64 architecture
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        # Broad SKU family selection for maximum availability and cost optimization
        - key: karpenter.azure.com/sku-family
          operator: In
          values: ["B", "D", "E", "F"]
      nodeClassRef:
        group: karpenter.azure.com
        kind: AKSNodeClass
        name: default
      taints:
        - key: karpenter.sh/capacity-type
          value: spot
          effect: NoSchedule
      expireAfter: Never
  disruption:
    # Aggressive consolidation for maximum cost optimization
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 0s
    budgets:
      - nodes: 50%
