# Organization-specific values (loaded from organization.yaml)
# These values can be overridden by environment variables for CI/CD
org: "${ORG_NAME:-msdp}"
base_domain: "${ORG_DOMAIN:-aztech-msdp.com}"
git_org: "${ORG_GITHUB:-msdp-platform}"
dictionary_ref: ./dictionary.yaml # canonical naming templates and constraints

cloud_providers:
  - aws
  - azure

default_regions:
  aws: "${AWS_DEFAULT_REGION:-eu-west-1}"
  azure: "${AZURE_DEFAULT_LOCATION:-uksouth}"

accounts:
  aws_account_id: "${AWS_ACCOUNT_ID:-319422413814}"
  azure_subscription_id: "${AZURE_SUBSCRIPTION_ID:-ecd977ed-b8df-4eb6-9cba-98397e1b2491}"

registries:
  ghcr: "${CONTAINER_REGISTRY:-ghcr.io/msdp-platform}" # GitHub Container Registry org scope
  aws_ecr: "${AWS_ECR_REGISTRY:-319422413814.dkr.ecr.eu-west-1.amazonaws.com}"
  azure_acr: "${AZURE_ACR_REGISTRY:-msdp.azurecr.io}"
default_registry: ghcr # use GHCR by default

naming:
  repo_shortname: infra
  project: msdp
  app: crossplane
  function: tfstate

oidc_validation:
  dev:
    aws_region: eu-west-1
    artifacts_path: infrastructure/environment/dev/artifacts/oidc/github-oidc-out.json

oidc:
  github_org: acme-inc
  audiences:
    - sigstore
    - api://AzureADTokenExchange

k8s_defaults:
  version: "1.29"
  ingress_class: nginx
  cert_issuer: letsencrypt-prod

# Derived names (do not set manually; scripts compute using dictionary.yaml)
# examples (computed):
#   cluster_name: {org}-{env}-{cloud}-{region}
#   namespace: {env}-{bu}-{app}
#   helm_release: {app}-{env}

autoscaling:
  nodes: karpenter
  pods: keda

dns:
  provider: "${DNS_PROVIDER:-route53}"
  route53_zone_id: "${ROUTE53_ZONE_ID:-Z0581458B5QGVNLDPESN}"

security_baseline:
  sign_images: false
  image_scan: true
  branch_protection: true

azure:
  kubernetesVersion: "1.29.7"
  location: "uksouth"
  subnetDiscoveryTags: { role: "aks" }
  networkProfile:
    plugin: "azure"
    policy: "azure"
    lbSku: "standard"
    outboundType: "loadBalancer"
  # defaults that env can override
  vnetCidrDefault: "10.50.0.0/16"
  subnetCidrDefault: "10.50.1.0/24"

  # --- Config Reference (AKS Matrix + Subnet Sizing) ---
  # The AKS workflow can deploy multiple clusters via a job matrix defined in the env config (config/envs/<env>.yaml):
  #
  #   azure:
  #     aksClusters:
  #       - name: aks-dev-a          # required; cluster and backend state name suffix
  #         size: medium             # optional; affects subnet size in Network (see size mapping below)
  #         # subnetName: snet-aks-dev-a  # optional override; defaults to "snet-<name>"
  #       - name: aks-dev-b
  #         size: large
  #
  # Size → newbits mapping (used by the Network workflow when computed_subnets_spec is generated):
  #   large  => newbits=8  => /24 subnets (for a /16 base_cidr)
  #   medium => newbits=9  => /25 subnets
  #   small  => newbits=10 => /26 subnets
  #
  # The Network workflow reads azure.vnetCidr as base_cidr and builds computed_subnets_spec from aksClusters.
  # The AKS workflow selects subnets by name via remote state: outputs.subnets["<subnetName>"].id.
paths:
  network: "infrastructure/environment/azure/network"
  aks: "infrastructure/environment/azure/aks"
