name: Azure AKS Clusters

on:
  push:
    branches: [main]
    paths:
      - "infrastructure/environment/azure/aks/**"
      - "config/dev.yaml"
  workflow_dispatch:
    inputs:
      action:
        description: "Action: plan (dry-run), apply (create/update), destroy (tear down). On push defaults to plan."
        required: true
        default: plan
        type: choice
        options: [plan, apply, destroy]
      environment:
        description: "Target environment (maps to config/<env>.yaml). On push defaults to dev."
        required: true
        default: dev
        type: choice
        options: [dev, staging, prod]
      cluster_name:
        description: "Exact cluster name from config/<env>.yaml (e.g., aks-msdp-dev-01). Leave empty to deploy all. If no match, deployment is skipped."
        required: false
        default: ""

permissions:
  id-token: write
  contents: read

env:
  TF_INPUT: "false"
  ARM_USE_OIDC: "true"
  # Resolved defaults for non-dispatch events (e.g., push)
  ACTION: ${{ github.event.inputs.action || 'plan' }}
  ENVIRONMENT: ${{ github.event.inputs.environment || 'dev' }}

jobs:
  prepare:
    if: ${{ always() && !cancelled() }}
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install PyYAML

      - name: Generate cluster matrix
        id: generate-matrix
        run: |
          python3 << 'EOF'
          import yaml
          import json
          import os
          import sys
          
          try:
              # Load configuration
              env = "${{ github.event.inputs.environment || 'dev' }}"
              cluster_filter = "${{ github.event.inputs.cluster_name }}"
              
              print(f"Loading configuration for environment: {env}")
              config_file = f'config/{env}.yaml'
              
              if not os.path.exists(config_file):
                  print(f"ERROR: Configuration file not found: {config_file}")
                  # Return empty matrix if config doesn't exist
                  matrix = {"include": []}
              else:
                  with open(config_file, 'r') as f:
                      config = yaml.safe_load(f)
                  
                  # Extract AKS clusters
                  clusters = config.get('azure', {}).get('aks', {}).get('clusters', [])
                  
                  if not clusters:
                      print(f"WARNING: No AKS clusters defined in {config_file}")
                      matrix = {"include": []}
                  else:
                      print(f"Found {len(clusters)} clusters in configuration")
                      
                      # Filter by cluster name if specified
                      if cluster_filter:
                          clusters = [c for c in clusters if c.get('name') == cluster_filter]
                          print(f"Filtered to {len(clusters)} clusters matching '{cluster_filter}'")
                      
                      # Add environment and network info to each cluster
                  for cluster in clusters:
                      cluster['environment'] = env
                      cluster['location'] = config.get('azure', {}).get('location', 'uksouth')
                      cluster.setdefault('resource_group_name', f"rg-{cluster['name']}")
                          
                          # Ensure all required fields have defaults
                          cluster.setdefault('kubernetes_version', '1.31.2')
                          cluster.setdefault('system_node_count', 2)
                          cluster.setdefault('system_vm_size', 'Standard_D2s_v3')
                          cluster.setdefault('user_vm_size', 'Standard_D4s_v3')
                          cluster.setdefault('user_min_count', 1)
                          cluster.setdefault('user_max_count', 5)
                          cluster.setdefault('user_spot_enabled', False)
                      
                      matrix = {"include": clusters}
              
              print(f"Generated matrix: {json.dumps(matrix, indent=2)}")
              
              # Write to GitHub output
              with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
                  f.write(f"matrix={json.dumps(matrix)}\n")
                  
          except Exception as e:
              print(f"ERROR generating matrix: {e}")
              # Return empty matrix on error
              matrix = {"include": []}
              with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
                  f.write(f"matrix={json.dumps(matrix)}\n")
              sys.exit(1)
          EOF

  check-matrix:
    needs: prepare
    runs-on: ubuntu-latest
    if: ${{ always() && !cancelled() }}
    outputs:
      has-clusters: ${{ steps.check.outputs.has-clusters }}
    steps:
      - name: Check if matrix has clusters
        id: check
        env:
          MATRIX: ${{ needs.prepare.outputs.matrix }}
        run: |
          echo "Matrix content: $MATRIX"
          HAS=false
          if [ -n "$MATRIX" ] && echo "$MATRIX" | jq -e '.include | type=="array" and length>0' >/dev/null 2>&1; then
            HAS=true
          fi
          echo "Has clusters: $HAS"
          if [ "$HAS" = "true" ]; then
            echo "has-clusters=true" >> $GITHUB_OUTPUT
          else
            echo "has-clusters=false" >> $GITHUB_OUTPUT
          fi
          
          # Debug output
          echo "=== Matrix Check Debug ==="
          echo "Matrix: $MATRIX"
          echo "Has clusters: $HAS"
          echo "Output set to: $(grep has-clusters $GITHUB_OUTPUT | cut -d= -f2)"

  deploy:
    needs: [prepare, check-matrix]
    runs-on: ubuntu-latest
    if: ${{ always() && !cancelled() && needs.check-matrix.outputs.has-clusters == 'true' }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}
    
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_USE_OIDC: "true"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install PyYAML

      - name: Cloud Login
        uses: ./.github/actions/cloud-login
        with:
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-1
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Generate Terraform Variables
        working-directory: infrastructure/environment/azure/aks
        run: |
          cat << 'SCRIPT' > generate_tfvars.py
          import yaml
          import json
          import os
          
          # Load configuration
          with open('../../../../config/${{ matrix.environment }}.yaml', 'r') as f:
              config = yaml.safe_load(f)
          
          # Extract cluster-specific configuration from JSON string
          cluster_config_json = '''${{ toJson(matrix) }}'''
          cluster_config = json.loads(cluster_config_json)
          tags = config.get('tags', {})
          
          # Get tenant ID from environment (set by GitHub secrets)
          tenant_id = os.environ.get('ARM_TENANT_ID', '')
          
          # Generate terraform.tfvars.json
          tfvars = {
              'cluster_name': cluster_config.get('name', ''),
              'kubernetes_version': cluster_config.get('kubernetes_version', '1.31.2'),
              'resource_group_name': cluster_config.get('resource_group_name', f"rg-{cluster_config.get('name', 'aks')}"),
              'location': cluster_config.get('location', config.get('azure', {}).get('location', 'uksouth')),
              'tenant_id': tenant_id,  # Use the secret value from environment
              'system_node_count': cluster_config.get('system_node_count', 2),
              'system_vm_size': cluster_config.get('system_vm_size', 'Standard_D2s_v3'),
              'user_vm_size': cluster_config.get('user_vm_size', 'Standard_D4s_v3'),
              'user_min_count': cluster_config.get('user_min_count', 1),
              'user_max_count': cluster_config.get('user_max_count', 5),
              'user_spot_enabled': cluster_config.get('user_spot_enabled', False),
              'network_plugin': cluster_config.get('network_plugin', 'kubenet'),
              'availability_zones': cluster_config.get('availability_zones', ["1", "2", "3"]),
              'max_pods_per_node': cluster_config.get('max_pods_per_node', 30),
              'os_disk_size_gb': cluster_config.get('os_disk_size_gb', 128),
              'tags': tags
          }
          
          with open('terraform.tfvars.json', 'w') as f:
              json.dump(tfvars, f, indent=2)
          
          print("Generated terraform.tfvars.json:")
          # Don't print tenant_id in logs
          tfvars_display = tfvars.copy()
          tfvars_display['tenant_id'] = '***'
          print(json.dumps(tfvars_display, indent=2))
          SCRIPT
          
          python3 generate_tfvars.py

      - name: Setup Terraform Backend
        uses: ./.github/actions/terraform-backend-enhanced
        with:
          environment: ${{ matrix.environment }}
          platform: azure
          component: aks
          instance: ${{ matrix.name }}
          aws_region: eu-west-1
          create_resources: "true"

      - name: Terraform Init
        uses: ./.github/actions/terraform-init
        with:
          working-directory: infrastructure/environment/azure/aks
          backend-config-file: ${{ env.TF_BACKEND_CONFIG_FILE }}
          terraform-version: 1.9.5

      - name: Terraform Plan
        if: ${{ env.ACTION == 'plan' || env.ACTION == 'apply' }}
        working-directory: infrastructure/environment/azure/aks
        run: |
          terraform plan -out=tfplan
          echo "✅ Terraform plan completed successfully for ${{ matrix.name }}"

      - name: Terraform Apply
        if: ${{ env.ACTION == 'apply' }}
        working-directory: infrastructure/environment/azure/aks
        run: |
          terraform apply -auto-approve tfplan
          echo "✅ Terraform apply completed successfully for ${{ matrix.name }}"

      - name: Show Outputs
        if: ${{ env.ACTION == 'apply' }}
        working-directory: infrastructure/environment/azure/aks
        run: |
          echo "=== AKS Cluster ${{ matrix.name }} Outputs ==="
          terraform output -json | jq .

      - name: Terraform Destroy
        if: ${{ env.ACTION == 'destroy' }}
        working-directory: infrastructure/environment/azure/aks
        run: |
          echo "⚠️  WARNING: This will destroy AKS cluster ${{ matrix.name }}!"
          terraform destroy -auto-approve
