name: aks
on:
  push:
    branches: [main]
    paths: ["config/**", "infrastructure/environment/azure/aks/**"]
  workflow_dispatch:
  workflow_run:
    workflows: ["azure-network"]
    types: [completed]

jobs:
  run:
    uses: ./.github/workflows/_tf_plan_apply.yml
    with:
      working_directory: infrastructure/environment/azure/aks
      env_config_path: config/envs/dev.yaml
      backend_key: aks/dev.tfstate
      apply: true
      extra_vars: "global_config_path=config/global.yaml"
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_BACKEND_BUCKET: ${{ secrets.TF_BACKEND_BUCKET }}
      TF_BACKEND_DDB: ${{ secrets.TF_BACKEND_DDB }}
