# NOTE: Config-driven workflow. Values are read from
# - infrastructure/config/globals.yaml (global defaults)
# - config/envs/<env>.yaml (environment specifics)
# This workflow supports naming-driven creation and controlled destroy.
name: aks

on:
  push:
    branches: [dev, main]
    paths:
      - "infrastructure/environment/azure/aks/**"
      - "config/**"
      - "infrastructure/config/**"
  workflow_dispatch:
    inputs:
      action:
        description: plan | apply | destroy
        required: true
        default: plan
        type: choice
        options: [plan, apply, destroy]
      env:
        description: Environment name (used to resolve config paths)
        required: false
        default: dev
        type: choice
        options: [dev, test, prod]
      team:
        description: Team name used for naming (e.g., red, blue, green)
        required: false
        default: ""
      region:
        description: Azure region (when provided, overrides globals.yaml)
        required: false
        default: ""
      size:
        description: Optional cluster size (small|medium|large) for vnet/subnet naming and node caps
        required: false
        default: ""
      create_rg:
        description: Create the Resource Group if it does not exist
        required: false
        default: false
        type: boolean
      manage_network:
        description: Auto-create VNet/Subnet if they don't exist
        required: false
        default: false
        type: boolean
      destroy_scope:
        description: Destroy scope when action=destroy
        required: false
        default: aks_only
        type: choice
        options: [aks_only, aks_and_network, resource_group]

permissions:
  id-token: write
  contents: write

env:
  TF_INPUT: "false"
  ARM_USE_OIDC: "true"

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.gen.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - name: Bootstrap environment
        uses: ./.github/actions/bootstrap-env
        with:
          env: ${{ inputs.env || 'dev' }}
      - name: Generate cluster matrix from config
        id: gen
        shell: bash
        run: |
          set -euo pipefail
          CFG_ENV="${TF_VAR_env_config_path:-config/envs/${{ inputs.env || 'dev' }}.yaml}"
          if [ -n "${INPUT_TEAM:-}" ]; then
            MATRIX=$( python3 ./.github/scripts/aks.py gen-matrix --cfg-env "$CFG_ENV" --team "$INPUT_TEAM" --env-id "${{ inputs.env }}" )
          else
            MATRIX=$( python3 ./.github/scripts/aks.py gen-matrix --cfg-env "$CFG_ENV" )
          fi
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT
        env:
          INPUT_TEAM: ${{ inputs.team || '' }}

  plan-apply:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.prepare.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4

      # Azure OIDC
      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Export ARM env
        shell: bash
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV

      # AWS OIDC for S3 backend of AKS state
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Bootstrap environment
        uses: ./.github/actions/bootstrap-env
        with:
          env: ${{ inputs.env || 'dev' }}

      # Backend creation + config (reusable, S3+DDB)
      - name: Terraform Backend (AWS)
        uses: ./.github/actions/terraform-backend
        with:
          repo-shortname: infra
          project: msdp
          env: ${{ inputs.env || 'dev' }}
          cloud: aws
          cloud-segment: azure
          app: aks
          function: tfstate
          key-salt: infrastructure/environment/azure/aks
          aws-region: eu-west-1
          use-shared-lock-table: "true"
          pipeline-name: aks-${{ matrix.name }}

      - name: Terraform Init (Reusable)
        uses: ./.github/actions/terraform-init
        with:
          working-directory: infrastructure/environment/azure/aks
          terraform-version: 1.13.2
          backend-config-file: ${{ env.TF_BACKEND_CONFIG_FILE }}

      - name: Show backend state key
        shell: bash
        run: |
          set -euo pipefail
          CONFIG="${{ env.TF_BACKEND_CONFIG_FILE }}"
          if [ -f "$CONFIG" ]; then
            echo "Backend state key: $(jq -r '.key' "$CONFIG")"
          else
            echo "Backend config file not found: $CONFIG" >&2
          fi

      - name: Resolve names and build aks.auto.tfvars.json
        id: build
        working-directory: infrastructure/environment/azure/aks
        shell: bash
        run: |
          set -euo pipefail
          CFG_GLOBAL="${TF_VAR_global_config_path:-infrastructure/config/globals.yaml}"
          CFG_ENV="${TF_VAR_env_config_path:-config/envs/${{ inputs.env || 'dev' }}.yaml}"
          if [ -n "${INPUT_TEAM:-}" ]; then
            python3 ./.github/scripts/aks.py build-tfvars \
              --cfg-global "$CFG_GLOBAL" --cfg-env "$CFG_ENV" \
              --env-id "${{ inputs.env }}" --team "$INPUT_TEAM" \
              ${INPUT_REGION:+--region "$INPUT_REGION"} \
              ${INPUT_SIZE:+--size "$INPUT_SIZE"} \
              --manage-network "${{ inputs.manage_network || false }}" \
              --create-rg "${{ inputs.create_rg || false }}" \
              --out aks.auto.tfvars.json --outputs-file "$GITHUB_OUTPUT"
          else
            python3 ./.github/scripts/aks.py build-tfvars \
              --cfg-global "$CFG_GLOBAL" --cfg-env "$CFG_ENV" \
              --name "${{ matrix.name }}" \
              ${INPUT_REGION:+--region "$INPUT_REGION"} \
              ${INPUT_SIZE:+--size "$INPUT_SIZE"} \
              --manage-network "${{ inputs.manage_network || false }}" \
              --create-rg "${{ inputs.create_rg || false }}" \
              --out aks.auto.tfvars.json --outputs-file "$GITHUB_OUTPUT"
          fi
        env:
          INPUT_TEAM: ${{ inputs.team || '' }}
          INPUT_REGION: ${{ inputs.region || '' }}
          INPUT_SIZE: ${{ inputs.size || '' }}

      - name: Update env config and push changes
        shell: bash
        run: |
          set -euo pipefail
          CFG_ENV="${TF_VAR_env_config_path:-config/envs/${{ inputs.env || 'dev' }}.yaml}"
          python3 ./.github/scripts/aks.py update-config \
            --cfg-env "$CFG_ENV" \
            --rg '${{ steps.build.outputs.rg }}' \
            --vnet '${{ steps.build.outputs.vnet }}' \
            --subnet '${{ steps.build.outputs.subnet }}' \
            --aks '${{ steps.build.outputs.aks }}' \
            --location '${{ steps.build.outputs.location }}' \
            ${INPUT_SIZE:+--size "$INPUT_SIZE"}
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "$CFG_ENV"
          if ! git diff --cached --quiet; then
            git commit -m "aks: update ${CFG_ENV} with naming-driven values"
            git push
          else
            echo "No changes to commit"
          fi
        env:
          INPUT_SIZE: ${{ inputs.size || '' }}

      - name: Terraform plan
        if: ${{ inputs.action == 'plan' || inputs.action == 'apply' || github.event_name == 'push' }}
        working-directory: infrastructure/environment/azure/aks
        shell: bash
        run: terraform plan -out=tfplan

      - name: Terraform apply
        if: ${{ inputs.action == 'apply' || (github.event_name == 'push' && github.ref == 'refs/heads/dev') }}
        working-directory: infrastructure/environment/azure/aks
        shell: bash
        run: terraform apply -auto-approve tfplan || { terraform plan -out=tfplan && terraform apply -auto-approve tfplan; }

      - name: Destroy (AKS, optional network/RG)
        if: ${{ inputs.action == 'destroy' }}
        working-directory: infrastructure/environment/azure/aks
        shell: bash
        run: |
          set -euo pipefail
          DEL_SCOPE='${{ inputs.destroy_scope || 'aks_only' }}'
          DEL_RG=false; DEL_NET=false
          if [ "$DEL_SCOPE" = "resource_group" ]; then DEL_RG=true; fi
          if [ "$DEL_SCOPE" = "aks_and_network" ]; then DEL_NET=true; fi
          python3 ./.github/scripts/aks.py destroy \
            --rg '${{ steps.build.outputs.rg }}' \
            --vnet '${{ steps.build.outputs.vnet }}' \
            --subnet '${{ steps.build.outputs.subnet }}' \
            --delete-rg "$DEL_RG" \
            --delete-network "$DEL_NET"