name: azure-network
on:
  push:
    branches: [main]
    paths:
      - "infrastructure/environment/azure/network/**"
      - "config/**"
      - "infrastructure/config/**" # include if globals live here
  workflow_dispatch:
    inputs:
      action:
        description: plan | apply | destroy
        required: true
        default: plan
        type: choice
        options: [plan, apply, destroy]
      resource_group:
        required: true
      location:
        required: true
        default: westeurope
      vnet_name:
        required: true
        default: msdp-prod-vnet
      address_space:
        description: CSV list (e.g. 10.20.0.0/16)
        required: false
        default: ""
      subnets_json:
        description: JSON array of {name,cidr,nsg_name?}
        required: false
        default: ""
      base_cidr:
        required: false
        default: ""
      subnet_count:
        required: false
        default: "0"
      subnet_names:
        description: CSV (e.g. app,db,ops)
        required: false
        default: ""
      nsg_prefix:
        description: NSG name prefix (computed mode)
        required: false
        default: ""

permissions:
  id-token: write
  contents: read

env:
  TF_INPUT: "false"
  ARM_USE_OIDC: "true"

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Azure OIDC (for azurerm provider)
      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Export ARM env
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV

      # AWS OIDC (for S3/DynamoDB backend)
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Bootstrap environment
        uses: ./.github/actions/bootstrap-env
        with:
          env: dev

      # --- BACKEND: create/ensure S3+DDB and write backend-config.json ---
      - name: Terraform Backend (AWS)
        uses: ./.github/actions/terraform-backend
        with:
          repo-shortname: infra
          project: msdp
          env: dev
          cloud: aws
          cloud-segment: azure # key path segment; keeps state per cloud segment
          app: network # stack name
          function: tfstate
          key-salt: infrastructure/environment/azure/network
          aws-region: eu-west-1
          # optional: pipeline-name: custom-name-here
          # optional: allow-key-mutation: "false"
          use-shared-lock-table: "true"
          # optional: lock-table-name:

      # --- INIT using the generated backend-config.json (safe) ---
      - name: Terraform Init (Reusable)
        uses: ./.github/actions/terraform-init
        with:
          working-directory: infrastructure/environment/azure/network
          terraform-version: 1.13.2
          backend-config-file: ${{ env.TF_BACKEND_CONFIG_FILE }}

      - name: Build network.auto.tfvars.json
        if: ${{ github.event_name == 'workflow_dispatch' }}
        working-directory: infrastructure/environment/azure/network
        shell: bash
        run: |
          set -euo pipefail
          addr_csv="${{ github.event.inputs.address_space || '' }}"
          if [ -n "$addr_csv" ]; then
            # explicit mode
            addrs=$(printf '%s\n' "$addr_csv" | tr -s ' ' | tr ',' '\n' | jq -R . | jq -s .)
            sj="${{ github.event.inputs.subnets_json || '' }}"
            if [ -n "$sj" ]; then
              # validate JSON
              subnets=$(printf '%s' "$sj" | jq -c .)
            else
              subnets='[]'
            fi
            jq -n \
              --arg rg "${{ github.event.inputs.resource_group || '' }}" \
              --arg loc "${{ github.event.inputs.location || '' }}" \
              --arg vnet "${{ github.event.inputs.vnet_name || '' }}" \
              --argjson address_space "$addrs" \
              --argjson subnets "$subnets" \
              '{resource_group:$rg, location:$loc, vnet_name:$vnet, address_space:$address_space, subnets:$subnets}' \
              > network.auto.tfvars.json
          else
            # computed mode
            names_csv="${{ github.event.inputs.subnet_names || '' }}"
            if [ -n "$names_csv" ]; then
              names=$(printf '%s\n' "$names_csv" | tr -s ' ' | tr ',' '\n' | jq -R . | jq -s .)
            else
              names='[]'
            fi
            count="${{ github.event.inputs.subnet_count || '0' }}"
            newbits=8
            nsg_prefix="${{ github.event.inputs.nsg_prefix || '' }}"
            jq -n \
              --arg rg "${{ github.event.inputs.resource_group || '' }}" \
              --arg loc "${{ github.event.inputs.location || '' }}" \
              --arg vnet "${{ github.event.inputs.vnet_name || '' }}" \
              --arg base "${{ github.event.inputs.base_cidr || '' }}" \
              --argjson count "$count" \
              --argjson newbits "$newbits" \
              --argjson names "$names" \
              --arg nsg_prefix "$nsg_prefix" \
              '{resource_group:$rg, location:$loc, vnet_name:$vnet, base_cidr:$base, subnet_count:$count, subnet_newbits:$newbits, subnet_names:$names, nsg_prefix:$nsg_prefix}' \
              > network.auto.tfvars.json
          fi
          echo "Wrote $(pwd)/network.auto.tfvars.json"

      - name: Terraform plan
        if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.action == 'plan' || github.event.inputs.action == 'apply' }}
        working-directory: infrastructure/environment/azure/network
        run: terraform plan -out=tfplan

      - name: Terraform apply
        if: ${{ (github.event_name != 'workflow_dispatch' && github.ref == 'refs/heads/main' && github.event_name != 'pull_request') || github.event.inputs.action == 'apply' }}
        working-directory: infrastructure/environment/azure/network
        run: terraform apply -auto-approve tfplan || terraform plan -out=tfplan && terraform apply -auto-approve tfplan

      - name: Terraform destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        working-directory: infrastructure/environment/azure/network
        run: terraform destroy -auto-approve
