name: network
on:
  push:
    branches: [main]
    paths: ["infrastructure/environment/**/azure/network/**"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  TF_INPUT: "false"
  ARM_USE_OIDC: "true"

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Load config paths
      - name: Load config paths
        id: config
        run: |
          NETWORK_PATH=$(yq '.paths.network' infrastructure/config/local.yaml)
          PREFLIGHT_SCRIPTS_PATH=$(yq '.paths.preflight_scripts' infrastructure/config/local.yaml)
          echo "network_path=$NETWORK_PATH" >> $GITHUB_OUTPUT
          echo "preflight_scripts_path=$PREFLIGHT_SCRIPTS_PATH" >> $GITHUB_OUTPUT

      # Azure OIDC for azurerm
      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Export ARM env for Terraform
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV

      # AWS OIDC for S3/Dynamo backend
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Preflight
        run: bash ${{ steps.config.outputs.preflight_scripts_path }}/preflight-network.sh

      - name: Terraform init (S3 backend)
        working-directory: ${{ steps.config.outputs.network_path }}
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TF_BACKEND_BUCKET }}" \
            -backend-config="key=network/dev.tfstate" \
            -backend-config="region=${{ secrets.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ secrets.TF_BACKEND_DDB }}" \
            -backend-config="encrypt=true"

      - name: Terraform plan
        working-directory: ${{ steps.config.outputs.network_path }}
        run: terraform plan -var="env=dev" -out=tfplan

      - name: Terraform apply
        if: github.ref == 'refs/heads/main'
        working-directory: ${{ steps.config.outputs.network_path }}
        run: terraform apply -auto-approve tfplan
