name: test-docker-acr

on:
  workflow_dispatch:
    inputs:
      acr_name:
        description: "ACR name (e.g., myacr)"
        required: true
      repo:
        description: "Repository path under ACR (e.g., infra/docker-build-test)"
        required: false
        default: infra/docker-build-test
      extra_tags:
        description: "Extra tags (comma-separated)"
        required: false
        default: latest

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cloud Login (Azure OIDC)
        uses: ./.github/actions/cloud-login
        with:
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-1
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Docker build and push (ACR)
        uses: ./.github/actions/docker-build
        with:
          registry: acr
          acr_name: ${{ inputs.acr_name }}
          repository: ${{ inputs.repo }}
          context: .
          file: ./.github/actions/docker-build/test/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ inputs.extra_tags }}
          use_cloud_login: true
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

