name: test-docker-ghcr

on:
  workflow_dispatch:
    inputs:
      repo:
        description: "Image repo under GHCR owner (e.g., infra-docker-build-test)"
        required: false
        default: infra-docker-build-test
      extra_tags:
        description: "Extra tags (comma-separated)"
        required: false
        default: latest

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Call reusable docker-build workflow (GHCR)
        uses: ./.github/workflows/docker-build.yml
        with:
          registry: ghcr
          repository: ${{ inputs.repo }}
          context: .
          file: ./.github/actions/docker-build/test/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ inputs.extra_tags }}

