apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: argocd-applications
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - infrastructure-application.yaml
