apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: msdp-platform-components
  namespace: argocd
  labels:
    app.kubernetes.io/name: msdp-platform-components
    app.kubernetes.io/component: platform
    app.kubernetes.io/part-of: msdp-platform
spec:
  project: default
  source:
    repoURL: https://github.com/msdp-platform/msdp-devops-infrastructure
    targetRevision: HEAD
    path: infrastructure/platforms
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
